server:
  http:
    addr: 0.0.0.0:10001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:10002
    timeout: 1s
  task:
    tasks:
      -
        name: job1
        type: "once"
        #schedule: "5s" # "5s" "5m" "5h" "5h5m5s"
      - name: job2
        type: "once"
#        name: job3
#        type: "cron"
#        schedule: "@every 5s"
##        schedule: "*/5 * * * *"

data:
  database:
    addr: 127.0.0.1:3306
    user: root
    password: root
    database: study
    max_idle_conn : 2000
    max_open_conn: 20000
    max_idle_time: 30
    slow_threshold_millisecond: 10 # SQL执行超过10ms，就算慢sql

  redis:
    addr: 192.168.5.52:6379
    password: "123456"
    db: 6
    pool_size: 20

micro:
  lb:
    addr:
      - "192.168.5.51:20000"

log:
  level: info
  log_path: ./log
  max_size: 100 # 日志保留大小，以 M 为单位
  max_backups: 3 # 保留文件个数
  console: true # false为不打印到终端
  filename: userx.log


#cron 表达式
#  // 	┌───────── 分钟 (0 - 59)
#  // 	│ ┌─────── 小时 (0 - 23)
#  // 	│ │ ┌───── 日期 (1 - 31)
#  // 	│ │ │ ┌─── 月份 (1 - 12)
#  // 	│ │ │ │ ┌─ 星期几 (0 - 6, 或者 SUN - SAT)
#  // 	│ │ │ │ │
#  // 	│ │ │ │ │
#  // 	│ │ │ │ │
#  // 	* * * * *